CREATE TABLE IF NOT EXISTS users (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NAME TEXT NOT NULL,
  EMAIL TEXT NOT NULL,
  PASSWORD TEXT NOT NULL,
  CELLPHONE INTEGER NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
